services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade-trend-dryrun
    volumes:
      - "./:/freqtrade/user_data"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade-maxdd.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.dryrun.maxdd.sqlite
      --config /freqtrade/user_data/config/config.dryrun.micro.nosol.json
      --strategy TrendFollowingMaxDD
